### ISSUE TITLE
Unity Version

### ISSUE THREAD

**Issue by chraibi** [skeletor069/Rohingya#1]
When I try to open this project I get the following error 

![Screenshot 2019-06-17 20 22 00](https://user-images.githubusercontent.com/5772973/59627040-9f1cad00-913d-11e9-8632-9ce4d71d1c4b.png)

So, which version should I install?

![Screenshot 2019-06-17 20 21 39](https://user-images.githubusercontent.com/5772973/59627060-a93eab80-913d-11e9-8306-afd2e4b4297d.png)

**Comment by skeletor069** [comment]
You have to download the version 2018.2.14. 

- Please go to [https://unity3d.com/get-unity/download/archive](url)
- login to your unity account if you are not logged in
- Under Unity 2018.x tab, find the version 2018.2.14

![Screen Shot 2019-06-18 at 5 51 34 AM](https://user-images.githubusercontent.com/15325370/59652326-9653c780-918d-11e9-9f48-1b3ee53c4429.png)

- Click the Unity Hub button

You should get it on Unity Hub at this point
